In [10]:
import pandas as pd

In [11]:
data = pd.read_csv('train.csv')

In [12]:
# to show the unuipue value for each columns
for i in data.columns:
    print(i, data[i].nunique())

PassengerId 891
Survived 2
Pclass 3
Name 891
Sex 2
Age 88
SibSp 7
Parch 7
Ticket 681
Fare 248
Cabin 147
Embarked 3

In [13]:
# to show the nan value
for i in data.columns:
    print(i, data[i].isna().sum())

PassengerId 0
Survived 0
Pclass 0
Name 0
Sex 0
Age 177
SibSp 0
Parch 0
Ticket 0
Fare 0
Cabin 687
Embarked 2

In [14]:
# prompt: in the columns Embarke the nan value do drop
#data.dropna(subset=['Embarked'], inplace=True)

data = pd.get_dummies(data, columns=['Embarked'], drop_first=True)


# to drop column Cabin and Name
data.drop(['Cabin', 'Name','Ticket','PassengerId'], axis=1, inplace=True)

In [15]:
# to put mean value for nan value
data['Age'].fillna(data['Age'].mean(), inplace=True)
data.head(10)

<ipython-input-15-800452955>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(), inplace=True)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,0,3,male,22.000000,1,0,7.2500,False,True
1,1,1,female,38.000000,1,0,71.2833,False,False
2,1,3,female,26.000000,0,0,7.9250,False,True
3,1,1,female,35.000000,1,0,53.1000,False,True
4,0,3,male,35.000000,0,0,8.0500,False,True
5,0,3,male,29.699118,0,0,8.4583,True,False
6,0,1,male,54.000000,0,0,51.8625,False,True
7,0,3,male,2.000000,3,1,21.0750,False,True
8,1,3,female,27.000000,0,2,11.1333,False,True
9,1,2,female,14.000000,1,0,30.0708,False,False

In [16]:
#to do mapping value for columns Sex and Embarked
data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})
# data['Embarked_Q'] = data['Embarked_Q'].map({'S': 0, 'C': 1, 'Q': 2})

In [17]:
# to see how much value columns Age has
#data['Age'].value_counts()

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X = data.drop('Survived', axis=1)
y = data['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# built the model and traning
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# result
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8156424581005587
              precision    recall  f1-score   support

           0       0.83      0.86      0.85       105
           1       0.79      0.76      0.77        74

    accuracy                           0.82       179
   macro avg       0.81      0.81      0.81       179
weighted avg       0.81      0.82      0.82       179